
# SPDX-FileCopyrightText: 2023 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/github-workflow.json
---
name: Test with virtual cards

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test with Virtual Cards
    runs-on: ubuntu-latest

    services:
      card:
        image: registry.gitlab.com/hkos/virtual-piv/openfips201
        volumes:
        - /run/pcscd:/run/pcscd

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install -y
            libpcsclite-dev
            pcsc-tools

    - name: Check virtual card
      run: pcsc_scan -vt2

    # - name: Setup Go
    #   uses: actions/setup-go@v4
    #   with:
    #     go-version-file: go.mod
    #     check-latest: true
